### ISSUE TITLE
Peer search currently not working

### ISSUE THREAD

**Issue by frederikhegger** [xWiseWolfx/IOTANodeSharing#2]
Dear wisewolf,
unfortunately, the peer search functionality on https://nodesharing.wisewolf.de/ is not working anymore. I tried it on different days, with no luck.

Can you have a look please, since I my node crashed and I had to reinstall everything without a backup (peers config).

**Comment by NeumannCo** [comment]
Thanks for the heads-up. My hoster changed the whole infrastructure and it seems, the rights management is broken. I'm looking into it, but unfortunately don't have a clue right now, what exactly to look for.

**Comment by NeumannCo** [comment]
Ok, should be up and running again now :-)
